<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIr1b1oo\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIr1b1oo/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIr1b1oo.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIr1b1oo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIr1b1oo\appProdProjectContainer(array(
    'container.build_hash' => 'Ir1b1oo',
    'container.build_id' => '0151d73f',
    'container.build_time' => 1556940230,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIr1b1oo');
